### PR TITLE
Rebuilt docs for Biopython 1.74

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
For testing: https://markuspiotrowski.github.io/docs/1.74/api/

### CODE REVIEW

**Comment by MarkusPiotrowski** [comment]
@peterjc One question regarding our master = dev branch. I thought that the versioning scheme for dev is e.g. `1.79dev0` but now I see that there is another dot separator: `1.79.dev0`. Am I wrong?

**Comment by peterjc** [comment]
We've been using with a dot, see e.g. https://github.com/biopython/biopython/commit/70df33c365bedd5ecdb5f620e284352c6116e274

Update: https://biopython.org/wiki/Building_a_release is clearly using the dot too. I think this is the standard.

**Comment by peterjc** [comment]
Is the idea to test the output of your new configuration on the oldest version of the Sphinx API docs (just in case it breaks so there is minimal inconvenience)?

**Comment by MarkusPiotrowski** [comment]
> 
> 
> Is the idea to test the output of your new configuration on the oldest version of the Sphinx API docs (just in case it breaks so there is minimal inconvenience)?

No, I want to do them one by one, because it's quite laborious (it's really hard get Sphinx using the correct Biopython version) and some versions need some adjustment (e.g. 1.74 has no 'previous', up to 1.77 they all have `Alphabet`). So I want to do each version with a separate PR.

**Comment by peterjc** [comment]
A separate PR for each existing version of the API docs makes sense.

I was more interested in seeing the configuration changes (even if as you point out, the oldest docs release will be a little different) driving this.

**Comment by MarkusPiotrowski** [comment]
That's work in progress (e.g. the changes to .travis-tox.ini are Windows specific and irrelevant):
https://github.com/biopython/biopython/compare/master...MarkusPiotrowski:api_docs

**Comment by peterjc** [comment]
I might rework the version logic there (e.g. why have both ``version`` and ``current_version`` defined), but that wouldn't change the output.

Do you want me to merge this now?

**Comment by peterjc** [comment]
You are listed as a member of https://github.com/orgs/biopython/teams/team-biopython/members and that team does have write access to the docs repository, so you _should_ be able to merge PRs on this repository...

**Comment by MarkusPiotrowski** [comment]
image

**Comment by MarkusPiotrowski** [comment]
Is it possibly a branch-specific setting?

**Comment by peterjc** [comment]
Ah, now I understand - this is stricter than the main website repository because I expected this one to only usually be updated automatically via a deployment key from TravisCI:

Screenshot 2020-09-19 at 13 19 41

We could turn off that branch protection, or add you to the admin group (core team)?

**Comment by peterjc** [comment]
Oh should *I* just merge it?

**Comment by MarkusPiotrowski** [comment]
It's fine with me if you just merge it.

**Comment by peterjc** [comment]
Merged. What's ``objects.inv`` for?

**Comment by MarkusPiotrowski** [comment]
As far as I have understood it helps with cross-referencing Biopython content in other hompages that where built with Sphinx using the intersphinx extension: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

**Pull request merged**
